---
- hosts: localhost
  connection: local
  tasks:
    - name: checkout for ansible playbook
      git: 
        repo: 'https://github.com/anfederico/Flaskex.git'
        dest: /srv/checkout

    - name: read-write git checkout for github
      git:
        repo: https://github.com/anfederico/Flaskex.git 
        dest: /home/anfederico/

    - name: clone repository
      git:
        repo: 'https://github.com/anfederico/Flaskex.git'
        dest: /srv/checkout
        clone: yes 
        update: no

    - name: requirements file 
      pip:
         requirements: /srv/checkout/requirements.txt

    - name: execute script
      tags: run
      command: python /srv/checkout/app.py
